name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install the dependencies
        run: pip3 install pyinstaller
      - name: Run the tests
        run: |
          python3 test.py
      - name: Build the executable
        run: |
          pyinstaller --onefile tkinter.py
      - name: List all files
        run: |
          ls