name: GitHub Actions Demo
on: [push]
jobs:
  Build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install the dependencies
        run: pip3 install pyinstaller
      - name: Run the tests
        run: |
          python3 test.py
      - name: Build the executable
        run: |
          pyinstaller --onefile gui.py
      - name: List all files
        run: |
          ls dist
  
  Build-on-Windows:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install the dependencies
        run: pip3 install pyinstaller
      - name: Run the tests
        run: |
          python3 test.py
      - name: Build the executable
        run: |
          pyinstaller --onefile gui.py
      - name: List all files
        run: |
          ls dist